<!doctype html>
<html>

  <head>
    <meta charset="utf-8">
    <title>Project 3 | <?php echo "$currentPage"; ?></title>

    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" href="css/navigation.css">

    <title> <?php echo "$currentPage"; ?> </title>

  </head>

  <body>

  	<div class = "container">
    
      <header>
        <h1><a href="index.php">Project 3</a></h1>
      </header>